Utilisation Leaflet JS + tile CARTO
Coasters-World/captain-coaster pull request #56
Opened 2022-07-02 18:35 UTC by shARPII

Je suis parti sur l'utilisation de https://github.com/CartoDB/basemap-styles avec la librairie Leaflet pour arrêter d'utiliser google maps. On pourra changer les marqueurs par des trucs de couleur quand on aura le ranking de parc.

2022-07-03 13:42 UTC, shARPII commented
@florian987 tu peux lier à l'issue #49

2022-07-04 20:34 UTC, florian987 requested changes

2022-07-04 20:34 UTC, florian987 commented on templates/Maps/index.html.twig
> +    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mapbox-gl/1.13.1/mapbox-gl.min.css" />
Tu dois avoir un block twig pour mettre les CSS

2022-07-04 20:39 UTC, florian987 commented on templates/Maps/index.html.twig
> +      map = L.map('map').setView([48.384098, 7.970846], 5);
Tu as retiré la fonctionalité pour récupérer la localisation du navigateur, pourquoi ?

2022-07-16 14:12 UTC, shARPII commented on templates/Maps/index.html.twig
> +    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mapbox-gl/1.13.1/mapbox-gl.min.css" />
Pas sûr d'avoir compris ce que tu voulais faire mais du coup j'ai ajouté les js/css au projet pour utiliser twig.

2022-07-16 14:21 UTC, shARPII commented
![image](https://pics.sharpopopo.fr/yipo4/kenIlorO46.png/raw)
Image de la map avec les nouveaux marqueurs (on pourra changer la couleur de la bordure plus tard)

2022-07-19 10:06 UTC, merged